### PR TITLE
Sn ia dd tweaks

### PR DESCRIPTION
**Pull request by kweide**
Hydro.F90.timersFix, use for SNIa_DoubleDetonation

### CODE REVIEW

**Comment by kweide** [comment]
@jaharris87 Will you take over again, merging this branch `SNIa_DD_tweaks` to master, once I have merged it into `staged`?

**Comment by jaharris87** [comment]
> @jaharris87 Will you take over again, merging this branch `SNIa_DD_tweaks` to master, once I have merged it into `staged`?

Yes, you will launch the test-suite?

**Comment by kweide** [comment]
Yes, I'll launch the tests.

**Comment by kweide** [comment]
Flash-Staged tests completed successfully.

**Pull request merged**
