### PR TITLE
RadTransTwoMoment Unit

### PR DESCRIPTION
**Pull request by jaharris87**
This adds the RadTrans/RadTransTwoMoment unit with an interface to Thornado for neutrino transport.
This includes re-introducing Driver_sourceTerms to Driver_evolveFlash (similar for Driver_initSourceTerms), and moving calls to Burn and RadTrans into this routine.
I will add a regression test for this in a future branch/PR (with a new Simulation setup).

This changes the maximum allowed string length for UNK labels from 4 to `MAX_STRING_LENGTH`. I did my best to test that this does not break any existing functionality:
* merged into development and ran all unit tests and regression tests listed in main FLASH5 ReadMe.
* tested read/write of checkpoint (both with new version) and compared results with sfocu
* tested restart from legacy checkpoint generated from master branch for Sod problem and compared results with sfocu

However, I would appreciate a review from someone familiar with the IO unit (@kweide ?) to put me at ease with these changes.

### CODE REVIEW

**Comment by jaharris87** [comment]
I don't know about pnetcdf. There is not a directory in `IO/IOMain` at the moment for `pnetcdf`, so I did not test it (+pnetTypeIO and +pnetcdf both fail at setup).

I also had not tested plot files, but this is a good point. I went ahead and tested by running the Sod problem with pm4dev. Plot files after 20 steps agree (from h5dump output), but there's a caveat here: The VisIt plugin doesn't quite know what to do with the new labels.

**Comment by kweide** [comment]
I think plot files have a sort of directory of included variables, in which the variable names are stored with a hardwired size of 4 bytes each. (I am not talking about the use of variable names for HDF5 data set names, but some additioonal data structure that is added by FLASH.) I assume your changes affect the way this directory is stored. And an application that tries to read such files and assumes this hardwired size will now fail.

**Comment by jaharris87** [comment]
> I think plot files have a sort of directory of included variables, in which the variable names are stored with a hardwired size of 4 bytes each. (I am not talking about the use of variable names for HDF5 data set names, but some additioonal data structure that is added by FLASH.) I assume your changes affect the way this directory is stored. And an application that tries to read such files and assumes this hardwired size will now fail.

🤦‍♂

**Comment by kweide** [comment]
Re the IO plot file problem: Something that __might__ work well enough is the following. Keep storing variable names with the new increased lenght throughout the FLAHS code. Only when it comes to writing the "directory" in plot files that I mentioned, limit the length of each name to 4 characters.  I assume that means that Visit will show these shortened names in its user interface (dropdown for variables in particular).

I don't know whether variables whose names have been shortened will actually be displayable...

**Comment by kweide** [comment]
Another thing that should be tested is restartability of checkpoint files.

We cannot currently restart when The Grid implementation is Amrex. I think restart should work when the Grid is Paramesh, although we are not currently testing this. We should make sure that this change does not make the situation worse for restarts.

**Comment by jaharris87** [comment]
> Another thing that should be tested is restartability of checkpoint files.
> 
> We cannot currently restart when The Grid implementation is Amrex. I think restart should work when the Grid is Paramesh, although we are not currently testing this. We should make sure that this change does not make the situation worse for restarts.

I did this by making sure I could restart from old checkpoints with the new code and new checkpoints from the new code, but not new checkpoints from the old code.

**Comment by jaharris87** [comment]
> I have been comparing the new RadTrans unit with the RadTrans unit that exists in FLASH 4.
> There are some differences which couldbe eliminated, in the interest of avoiding unnecessary divergences. I have no strong opinions on this though.
> 
> Well, after looking more closely, I don't really see unnecessary divergence, but an inconsistency in your implementation: Is` RadTrans()` to be called directly from `Driver_evolveFlash`, or indirectly via `Driver_sourceTerms`? The current new implementation appears to do both.
> The way that is consistent with FLASH4 would be to call `RadTrans` directly from `Driver_evolveFlash`. (Yes, it is somewhat inconsistent that the `_init` and `_finalize` calls are done via `Driver_{init,finalize}SourceTerms` anyway.)

Thanks for catching this, I'll fix and push it along.

**Comment by jaharris87** [comment]
2f21e9e fixes all issues with plot files.

ed97fbc addresses the other issue with double-call of RadTrans.

I did not have to resort to the strategy you suggested with limiting plotfile variable names.

Regarding this comment:
> We cannot currently restart when The Grid implementation is Amrex.
Do you know what the issue is here? This is a pretty sever limitation.

**Comment by jaharris87** [comment]
If @kweide is happy with this, could either @jared321 or Klaus launch merge this and launch the Flash-staged tests? I don't think I have permissions to do this.

**Comment by smcouch** [comment]
Hi all, just catching up on this. Since I plan to put our M1 transport into FLASH5 at some point I thought I should opine. I think `RadTrans` should be called from `Driver_evolveFlash` not `Driver_sourceTerms`, as is done in FLASH4, since `RadTrans` is more than just a source term.

Also, on variable names, it sounds like you have figured out a solution so this is not needed, but they way we do it for M1 in FLASH4 is to use two letters for the radiation variable and two numbers for the group, all generated by the Python config file generation business. Our M1 Config file is copied below. 

```Python
##python:genLines

def genLines(setupvars):
    # Config file for RadTrans/RadTransMain/M1 unit implementation directory

   NDIM = int(setupvars['nDim'])

   yield 'PPDEFINE NGROUPS %d' % int(setupvars['m1_groups'])
   yield 'PPDEFINE FLASH_M1'
   yield 'USESETUPVARS useHybridEOS'
   yield 'IF useHybridEOS'
   yield '   REQUIRES physics/Eos/EosMain/Hybrid'
   yield 'ELSE'
   yield '   REQUIRES physics/Eos/EosMain/Nuclear'
   yield 'ENDIF'
   yield 'PARAMETER rt_useRadTrans BOOLEAN TRUE'
   yield 'PARAMETER rt_opacTable STRING "file.dat"'
   yield 'PARAMETER rt_NumGroups INTEGER 1'
   yield 'PARAMETER rt_rkTime BOOLEAN FALSE'
   yield 'PARAMETER rt_doies BOOLEAN FALSE'
   yield 'PARAMETER rt_doVel BOOLEAN FALSE'
   yield 'PARAMETER rt_labframe BOOLEAN TRUE'
   yield 'PARAMETER rt_pushFac REAL 1.0'

   yield 'VARIABLE DEPS'
   yield 'VARIABLE DYE'
   yield 'VARIABLE DMOX'
   yield 'VARIABLE PVLX'
   yield 'VARIABLE PVLY'
   yield 'VARIABLE PVLZ'

   yield 'VARIABLE YNU'
   yield 'VARIABLE ENUE'
   yield 'VARIABLE ENUA'
   yield 'VARIABLE ENUX'
   yield 'VARIABLE RNUE'
   yield 'VARIABLE RNUA'
   yield 'VARIABLE RNUX'
   yield 'VARIABLE MNUE'
   yield 'VARIABLE MNUA'
   yield 'VARIABLE MNUX'
   yield 'VARIABLE HNUE'
   yield 'VARIABLE HNUA'
   yield 'VARIABLE HNUX'
   yield 'VARIABLE FNUE'
   yield 'VARIABLE FNUA'
   yield 'VARIABLE FNUX'
   yield 'VARIABLE PNUE'
   yield 'VARIABLE PNUA'
   yield 'VARIABLE PNUX'


   if NDIM > 1:
      yield 'VARIABLE DMOY'
   if NDIM == 3:
      yield 'VARIABLE DMOZ'

   if "m1_groups" in setupvars:
      m1_groups = int(setupvars['m1_groups'])
      m1_nflux = 3*(m1_groups + m1_groups*NDIM)
      yield 'PPDEFINE RT_NFLUX %d' % m1_nflux
      for N in range(1,m1_groups+1):
      	  yield 'VARIABLE EE%.2d' % N
	  yield 'VARIABLE EA%.2d' % N
	  yield 'VARIABLE EX%.2d' % N
	  yield 'VARIABLE FE%.2d' % N
	  yield 'VARIABLE FA%.2d' % N
	  yield 'VARIABLE FX%.2d' % N
          if NDIM > 1:
	     yield 'VARIABLE GE%.2d' % N
	     yield 'VARIABLE GA%.2d' % N
	     yield 'VARIABLE GX%.2d' % N
          if NDIM == 3:
	     yield 'VARIABLE HE%.2d' % N
	     yield 'VARIABLE HA%.2d' % N
	     yield 'VARIABLE HX%.2d' % N
   else:
      yield 'SETUPERROR Must specify m1_groups!'

   for b in xrange(m1_groups+1):
      yield 'PARAMETER rt_m1Bounds_%d REAL -1.0' % (b+1)

   yield 'USESETUPVARS threadWithinBlock'
   yield 'IF threadWithinBlock'
   yield '   PARAMETER threadM1WithinBlock BOOLEAN TRUE'
   yield 'ELSE'
   yield '   PARAMETER threadM1WithinBlock BOOLEAN FALSE'
   yield 'ENDIF'
```

**Comment by jaharris87** [comment]
Thanks for the feedback @smcouch 

We removed RadTrans from the sourceTerms call, and I agree that it is more than just a source term.
Our solution to the variable naming was similar to yours, but was originally complicated by the need for a spatial node index for DG, in addition to the energy groups. Moving to the grid-coarsening, I don't think this is necessary. But still, maybe one day we'll want to run with more than 100 energy groups 🤣

**Comment by smcouch** [comment]
Agreed! I thought about this when we came up with the workaround. 

Someday... 100 groups.... I kinda hope we never need to do that :)

**Comment by kweide** [comment]
@jaharris87 Are there any remaining known issues with using variable names with more than 4 characters, in plot files or elsewhere?

**Comment by kweide** [comment]
Apparently there are remaining issues. I ran a Flash-Development test suite through Jenkins.
It appears that all comparison tests fail. Sfocu seems unable to compare any of the newly created checkpoint files to their benchmarks. I assume that this has to do with the IO changes for variable names.

**Comment by jaharris87** [comment]
> Apparently there are remaining issues. I ran a Flash-Development test suite through Jenkins.
> It appears that all comparison tests fail. Sfocu seems unable to compare any of the newly created checkpoint files to their benchmarks. I assume that this has to do with the IO changes for variable names.

Not that I've encountered or been able to find.

**Comment by kweide** [comment]
Sample output from failing sofocu from the test run:
[test_output.txt](https://github.com/ECP-Astro/FLASH5/files/3763362/test_output.txt)

**Comment by jaharris87** [comment]
Can you try this with a rebuilt sfocu after 469c3f8 ?
I think it might still fail, but it will fail differently.

**Comment by kweide** [comment]
Not much point in running the whole test suite again if we already know it 
is broken.

**Comment by kweide** [comment]
Anyway I am running Flash-Development tests again. It will take a while until the test suite reaches those Comparison tests.

**Comment by jaharris87** [comment]
Ok, I think I see the problem. I was able to produce a legacy checkpoint I can use to diagnose this. You're right though, the test will fail.

**Comment by kweide** [comment]
But (whether this works or not with a modified sfocu - __any__ modified sfocu) it seems pretty clear that we are now generating FLASH HDF5 files that are incompatible with older FLASH HDF5 files.

We should either own up to that fact by assigning a new format version number and writing that number to HDF5 files (which could in turn  lead to other programs, like Visit, refusing to read those files). Or we should back out these changes.

**Comment by jaharris87** [comment]
> But (whether this works or not with a modified sfocu - **any** modified sfocu) it seems pretty clear that we are now generating FLASH HDF5 files that are incompatible with older FLASH HDF5 files.

I'm not sure this is true. I can restart a simulation using the new format from a checkpoint written in the old format. I'm also able to visualize both formats in VisIt.

**Comment by kweide** [comment]
Ok, I'll run `Flash-Development` test suite again now.

Maybe we can revisit the name length limitation in a separate issue.

**Comment by kweide** [comment]
One test in `Flash-Development` failed, namely `Comparison_Cellular_AMR_2d_Paramesh_unsplit`.

The failing test produced only checkpoints numbered 0000..0002, instead of 0000..0003 as expected by the test configuration.

I think this is because of one of the changes made to `DriverMain/Unsplit/Driver_evolveFlash.F90` in 1f30b5940dc10fd6c875eb47a638dd03ae5b9a02, namely elimination of the line
```
  if(.NOT.endRun) call IO_outputFinal()
```

It is not clear why that line was removed, and I believe the line should be reinstated. It is a reasonable expectation of FLASH users that the code will always generate a checkpoint after the final time step, and this has traditionally the behavior.

**Comment by ranchu1** [comment]
It must be my fault. Thank you for pointing out.

**Comment by jaharris87** [comment]
The line has been reintroduced. Thanks for the catch.

**Comment by kweide** [comment]
Ok, retesting now.

**Comment by kweide** [comment]
No further problems with tests, ok, let's make progress merging this PR to staged. 

This unit still may need some tests, so I will label the next pull request as `needs_test`. If that's wrong, remove the label.

**Pull request merged**
