### PR TITLE
Bittree

### PR DESCRIPTION
**Pull request by tklos96**
Use Bittree=True in your setup command to enable the use of the Bittree package in Paramesh. This should reduce time spent in regridding by reducing MPI calls and eliminating some communication latency.

### CODE REVIEW

**Comment by kweide** [comment]
Testing with Intel compilers on compute002.mcs.anl.gov produces compile-time errors:
From `./setup -auto -3d -debug -nxb=8 -nyb=8 -nzb=8 +uhd +pm4dev Bittree=True -gridinterpolation=native -makefile=Intel -site=compute001.mcs.anl.gov`:
```
amr_calculate_tree_data.F90(243): error #8055: The procedure has a dummy argument that has the ALLOCATABLE, ASYNCHRONOUS, OPTIONAL, POINTER, TARGET, VALUE or VOLATILE attribute. Required explicit interface is missing from original source.
                                                       logpar,.TRUE.)
--------------------------------------------------------------^
compilation aborted for amr_calculate_tree_data.F90 (code 1)
make: *** [amr_calculate_tree_data.o] Error 1
```
and from `./setup DustCollapse -makefile=Intel -site=compute001.mcs.anl.gov -auto -2d +cylindrical +Mode1 Bittree=True +serialIO +uhd +newMpole -debug`:
```
mpi_amr_check_derefine.F90(61): remark #7712: This variable has not been used.   [MYPE]
      subroutine amr_check_derefine(mype)
------------------------------------^
mpi_amr_check_derefine.F90(78): remark #7712: This variable has not been used.   [IX]
      integer :: i,ix,iy,iz,ierr
-------------------^
mpi_amr_check_derefine.F90(78): remark #7712: This variable has not been used.   [IY]
      integer :: i,ix,iy,iz,ierr
----------------------^
mpi_amr_check_derefine.F90(78): remark #7712: This variable has not been used.   [IZ]
      integer :: i,ix,iy,iz,ierr
-------------------------^
mpi_amr_check_derefine.F90(87): remark #7712: This variable has not been used.   [FIRST]
      logical :: first
-----------------^
mpi_amr_check_derefine.F90(89): remark #7712: This variable has not been used.   [IERRORCODE]
      integer :: ierrorcode
-----------------^
mpi_amr_check_derefine.F90(151): error #8055: The procedure has a dummy argument that has the ALLOCATABLE, ASYNCHRONOUS, OPTIONAL, POINTER, TARGET, VALUE or VOLATILE attribute. Required explicit interface is missing from original source.   [GR_GETNEIGHINTCOORDS]
            call gr_getNeighIntCoords(i,gCell,neighCoord)
-----------------^
compilation aborted for mpi_amr_check_derefine.F90 (code 1)
make: *** [mpi_amr_check_derefine.o] Error 1
```

**Comment by tklos96** [comment]
Added some interfaces to hopefully fix these errors.

**Comment by kweide** [comment]
Now getting runtime errors.
This is from a test run as follows:
```
22:09:45 Parsed "compute001/Comparison/Sod/AMR/2d/pm4Bittree/simpleUnsplit"
22:09:45 Creating directory "/nfs2/kweide/flashTest/output/compute001/2019-10-30_6/Comparison_Sod_AMR_2d_pm4Bittree_simpleUnsplit"
         ****** "test.info" ******
         setupName: Sod
         setupOptions: -auto -2d -debug -nxb=8 -nyb=8 -unit=physics/Hydro/HydroMain/simpleUnsplit/HLL +pm4dev Bittree=True -gridinterpolation=native -makefile=Intel -site=compute001.mcs.anl.gov
         numProcs: 1
         shortPathToBenchmark: /homes/joneal/Projects/FlashTestSuite/<siteDir>/baselines/20176c17/Comparison_Sod_AMR_2d_Paramesh_simpleUnsplit/<runDir>/<chkMax>
         parfiles: <pathToSimulations>/Sod/test_amr_2d.par
```

```
 Grid_init: resolution based on runtime params:
  lrefine          dx              dy              dz
      1             0.125           0.125           0.125
      2             0.062           0.062           0.062
      3             0.031           0.031           0.031
      4             0.016           0.016           0.016
 MaterialProperties initialized
 Source terms initialized
 sim_rhoAmbient is   1.00000000000000     
  iteration, no. not moved =            0           0
 Done with refinement: total leaf blocks =            1
 Done with refinement: total blocks =            1
 [amr_morton_process]: Initializing surr_blks using standard orrery implementati
 on
 INFO: Grid_fillGuardCells is ignoring masking.
  iteration, no. not moved =            0           0
 Done with refinement: total leaf blocks =            8
 Done with refinement: total blocks =            9
  iteration, no. not moved =            0           0
 Done with refinement: total leaf blocks =           64
 Done with refinement: total blocks =           73
forrtl: severe (408): fort: (3): Subscript #5 of the array UNK has value -1 which is less than the lower bound of 1

Image              PC                Routine            Line        Source             
flash-exe          000000000177E2E9  Unknown               Unknown  Unknown
flash-exe          00000000013FCB0F  send_block_data_          456  send_block_data.F90
flash-exe          000000000112C65B  amr_redist_blk_           691  mpi_amr_redist_blk.F90
flash-exe          00000000008D30A0  amr_morton_order_         116  amr_morton_order_bittree.F90
flash-exe          00000000011B666C  amr_refine_derefi         249  mpi_amr_refine_derefine.F90
flash-exe          0000000000A50EEB  gr_expanddomain_          220  gr_expandDomain.F90
flash-exe          00000000004C722C  grid_initdomain_           98  Grid_initDomain.F90
flash-exe          0000000000420005  driver_initflash_         146  Driver_initFlash.F90
flash-exe          000000000045C1D5  MAIN__                     49  Flash.F90
flash-exe          000000000040D59E  Unknown               Unknown  Unknown
libc-2.19.so       00007FFA32716F45  __libc_start_main     Unknown  Unknown
flash-exe          000000000040D4A9  Unknown               Unknown  Unknown
forrtl: severe (408): fort: (3): Subscript #5 of the array UNK has value -1 which is less than the lower bound of 1
```

**Comment by tklos96** [comment]
Weird I can't reproduce the error. I'll have to look at it tomorrow.

**Pull request merged**
