### PR TITLE
Weaklib+unitTest

### PR DESCRIPTION
**Pull request by jaharris87**
Compiled and ran on Summit with the following setup: `./setup unitTest/Eos/WeakLib -auto -3d`

Merged into development and unit test still passes.
Structure is nearly identical to Helmholtz unit test.

Includes a somewhat large (~50MB) input data file (similar in size to `helm_table.dat`.
Also adds an additional interface to Eos_wrapped that uses the tile iterator to apply the Eos on all leaf blocks.

I believe this can be added to the regular test suite.

### CODE REVIEW

**Comment by jaharris87** [comment]
> `Eos_blkWrapped` seems to have the same function and interface as the `Eos_everywhere.F90` I invented a long time ago (and of which there is still a stub and an experimental implementation under physics/Eos and physics/Eos/EosMain). I find the name `Eos_blkWrapped` misleading and prefer my old name...

I do as well, but it relies on some routines that don't exist in +Mode3.
I don't mind renaming the routine, though, but I don't know if I want to make the `Grid_makeVector` routine for the AMReX interface.

**Comment by jaharris87** [comment]
@kweide How would you feel about this:

1. Rename `Eos_everywhere.F90` to `Eos_everywhere.F90.pm`
2. Move `Eos_blkWrapped` to `Eos_everywhere.F90.amrex`
3. Add this to `Config`:
```
LINKIF Eos_everywhere.F90.pm Grid/GridMain/AMR/paramesh
LINKIF Eos_everywhere.F90.pm Grid/GridMain/AMR/Amrex
```

**Comment by kweide** [comment]
On Tue, 22 Oct 2019, Austin Harris wrote:

> 1. Rename `Eos_everywhere.F90` to `Eos_everywhere.F90.pm`
> 2. Move `Eos_blkWrapped` to `Eos_everywhere.F90.amrex`
> 3. Add this to `Config`:
> ```
> LINKIF Eos_everywhere.F90.pm Grid/GridMain/AMR/paramesh
> LINKIF Eos_everywhere.F90.pm Grid/GridMain/AMR/Amrex
> ```


I suggest something simpler:   (`.exp` for experimental)

 1. Rename `Eos_everywhere.F90` to `Eos_everywhere.F90.exp`
 2. Move `Eos_blkWrapped` to `Eos_everywhere.F90`
 3. No modification to `Config`

Klaus

**Comment by jaharris87** [comment]
7ed6bc0..e002ffc addresses your suggestions @kweide 
These have been merged and tested in development.
Ready for merge into staged if you are.

**Comment by kweide** [comment]
Ok, shall I do the merge?

**Comment by jaharris87** [comment]
Please.

**Pull request merged**
